- name: 脱口秀大会第五季第一期上
  key: u0044od482k
  time: 90
- name: 脱口秀大会第五季第一期下
  key: u0044kvn0al
  time: 90
- name: 脱口秀大会第五季第二期上
  key: h0044mkvfk9
  time: 90
- name: 脱口秀大会第五季第二期下
  key: e0044ur28md
  time: 90
