- name: 脱口秀大会第五季第一期上
  key: u0044od482k
  time: 90
- name: 脱口秀大会第五季第一期下
  key: u0044kvn0al
  time: 90
- name: 脱口秀大会第五季第二期上
  key: h0044mkvfk9
  time: 90
- name: 脱口秀大会第五季第二期下
  key: e0044ur28md
  time: 90
- name: 脱口秀大会第五季第三期上
  key: y00445nfoyz
  time: 146
- name: 脱口秀大会第五季第三期下
  key: k00443j2327
  time: 104
- name: 脱口秀大会第五季第四期上
  key: u0044tp8ect
  time: 127
- name: 脱口秀大会第五季第四期下
  key: a0044buqb6q
  time: 109
- name: 脱口秀大会第五季第五期上
  key: m004451cuz0
  time: 78
- name: 脱口秀大会第五季第五期下
  key: q004417f8c7
  time: 76
- name: 脱口秀大会第五季第六期上
  key: j0044zhcule
  time: 68
- name: 脱口秀大会第五季第六期下
  key: b0044o6v375
  time: 77
- name: 脱口秀大会第五季第七期上
  key: k0044z2yufx
  time: 79
- name: 脱口秀大会第五季第七期下
  key: g0044y0jkce
  time: 64
- name: 脱口秀大会第五季第八期上
  key: q0044s8eno8
  time: 107
- name: 脱口秀大会第五季第八期下
  key: j00443m88ew
  time: 113
- name: 脱口秀大会第五季第九期上
  key: b0044krsgv5
  time: 106
- name: 脱口秀大会第五季第九期下
  key: t0044my7wcl
  time: 110
- name: 脱口秀大会第五季第十期上
  key: m00445blvij
  time: 132
- name: 脱口秀大会第五季第十期下
  key: g00448n91zg
  time: 112